### PR TITLE
Use importlib to import Python handlers

### LINKED ISSUE #90: [Python] Handlers inside a PEP 420  namespaces aren't working
# Handlers inside a PEP 420  namespaces aren't working

## Description

When a lambda using this layer tries to load the handler that comes from a module included in a namespace, the import fails.
For example, if your handler is under "namespace.package.handler", an exception will be returned saying that "namespace" isn't a package.

The issue is most likely coming from https://github.com/newrelic/newrelic-lambda-layers/blob/df3459626e17fd4843607a66e272c494e36b8f36/python/newrelic_lambda_wrapper.py#L61 as the modules are found and loaded using the "imp" module, which is deprecated since Python 3.4. 

The module "importlib" should be used instead. That would most likely solve this issue + avoid the for loop "imp" requires to load sub-modules.

## Steps to Reproduce

Define a handler that is inside a namespace (e.g. NEW_RELIC_LAMBDA_HANDLER=namespace.package.handler)
Run the lambda function.

## Expected Behaviour

The NR layer should be able to import the handler and run the lambda.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

Python3.9 (AWS Python runtime)

### PR DESCRIPTION
**Pull request by huonw**
This fixes #90 by switching the handler import code to use `importlib`, instead of the now deprecated `imp`. This has the side bonus of simplifying the code.

This matches the current `awslambdaric` bootstrapping code more closely (<https://github.com/aws/aws-lambda-python-runtime-interface-client/blob/97dee252434edc56be4cafd54a9af1e7fa041eaf/awslambdaric/bootstrap.py#L33-L39>)  following the changes in <https://github.com/aws/aws-lambda-python-runtime-interface-client/commit/620b14824600db3c32ba8e234e3175dbece8b8b5>.

---

I've tested this against a lambda deployed as a PEX (https://github.com/pantsbuild/pex).:

- Background: These are a self-contained executable (includes dependencies and so on) that does various magic to set up those dependencies when importing via a `__pex__` pseudo-package (https://github.com/pantsbuild/pex/pull/1845). If the pex has the handler `bar` in `foo.py`, this means the configuration has to be `NEW_RELIC_LAMBDA_HANDLER=__pex__.foo.bar`. 
- Before this patch: the `imp` module would find `__pex__` but not `foo` within it.
- After this patch: `importlib` will happily load `__pex__.foo` (and thus set up any dependencies) and the wrapper can find the `bar` handler within it.

### CODE REVIEW

**Comment by huonw** [comment]
Hi @mrickard, I'd love to see this land so that we can simplify our code that integrates with New Relic; do you have a chance to let me know what you think? Thanks!

**Comment by mrickard** [comment]
Thank you for contributing, @huonw ! Let me direct this one to the Python team for review.

**Comment by mrickard** [comment]
Apologies for the delay, @huonw ! I'll put this in front of the Python team again tomorrow.

**Review by hmstepanek — CHANGES_REQUESTED** [review]
Overall looks pretty good and thank you for the contribution! This is also good to do as it looks like imp will be removed in Python3.12. I had one major request which is to still catch import failures.

**Comment by huonw** [comment]
> This is also good to do as it looks like imp will be removed in Python3.12.

Ah, good catch 👍

**Review by hmstepanek — APPROVED** [review]
Looks good! Thank you again for contributing!

**Comment by huonw** [comment]
Done (thanks for the link)

**Comment by huonw** [comment]
Can I ask if this is likely to be released soon? (One of our developers tripped over the finicky work-around we're having to use, so it'd be nifty if we could upgrade our layer and remove the work-around.)

**Pull request merged**
