### PR TITLE
Implement Java 17 layers

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@newrelic please review

**Review by greg-swift-yohana — CHANGES_REQUESTED** [review]
Trying to get this working myself, and ran into a few things.

Offered up the suggested edits I could but distribution URL in gradle-wrapper.properties also needs to be updated to at least 7.6.1.

With all that changed...... now i'm getting testing errors, which could be a result of the language version differences but i haven't figured that out yet.

```
> Task :test

com.newrelic.java.HandlerWrapperTest > testRequestStreamHandler FAILED
    java.lang.reflect.InaccessibleObjectException at HandlerWrapperTest.java:39

com.newrelic.java.HandlerWrapperTest > testRequestWrongStreamHandler FAILED
    java.lang.reflect.InaccessibleObjectException at HandlerWrapperTest.java:48

com.newrelic.java.HandlerWrapperTest > testRequestWrongHandler FAILED
    java.lang.reflect.InaccessibleObjectException at HandlerWrapperTest.java:28

com.newrelic.java.HandlerWrapperTest > testRequestHandler FAILED
    java.lang.reflect.InaccessibleObjectException at HandlerWrapperTest.java:19

```

**Comment by gliptak** [comment]
@greg-swift-yohana thank you for review and updates

https://github.com/newrelic/newrelic-lambda-layers/blob/master/java/gradle/wrapper/gradle-wrapper.properties#L3 is kinda old

https://gradle.org/releases/

Gradle 7.6.2 is still seems compatible with Java 8

https://docs.gradle.org/current/userguide/compatibility.html

would you like to submit a Gradle 7.6.2 upgrade PR or I can proceed to do so

**Comment by greg-swift-yohana** [comment]
You are welcome to.

Also i forgot to mention that the build.gradle needs to support java17 as well.

I'm still fighting the java17 test failures.

Seems that [RequestHandler with Java17 leans on Records](https://docs.aws.amazon.com/lambda/latest/dg/java-handler.html), but I can't figure out a valid change to make that work.

**Comment by gliptak** [comment]
yes Gradle 7.6.2 is compatible with Java 17

**Comment by greg-swift-yohana** [comment]
What I meant by `build.gradle` needs to support Java 17 is this chunk of code:

```
ext.javaVersion = hasProperty('javaVersion') && project.getProperty('javaVersion') == 11 ?
        JavaVersion.VERSION_11 : JavaVersion.VERSION_1_8

java {
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
}
```

For testing purposes I'm just doing this for now.

```
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
``` 

I think the reason the tests are failing is because its an "illegal-access" issue starting with java17 so i'm trying to find the documentation on all the switches that are needed in this

**Comment by greg-swift-yohana** [comment]
I am trying to permit that for testing, but actually addressing it seems like the better path? 

https://openjdk.org/jeps/403

**Comment by gliptak** [comment]
@greg-swift-yohana please review #175

**Pull request merged**
